### ISSUE TITLE
Selective trashing

### ISSUE THREAD

**Issue by ghost** [lunaryorn/osx-trash.el#1]
Is there a way to make this only call trash for files interactively deleted by user in `dired` for example?

**Comment by swsnr** [comment]
No, there isn't, and there won't be.  It's outside the scope and purpose of this package:  `delete-by-moving-to-trash` is a standard Emacs feature, and this this package just ports to OS X, but does not otherwise extend or modify it. 

Please use `M-x report-emacs-bug` to suggest this to the Emacs developers.
